name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - actions

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pattern: [0]
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          mkdir build && cd build
          echo WORKSPACE-----$GITHUB_WORKSPACE
          echo HOME-----$HOME
          echo GITHUB_EVENT_PATH-----$GITHUB_EVENT_PATH
          xx
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: buildlog
          path: $GITHUB_WORKSPACE/build

