name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'
    tags:
    - '*'

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
        pattern: [0, 1]
    steps:
#       - uses: actions/checkout@v2.0.0
      - name: build
        run: |
          try {
            ls a 2>$null
            if (!$?) {
              echo shibail
              ls 
            } else {
              echo xxxxxxxxxxxxx
            }
          } catch {
            echo incatch
            pwd
            echo endend
          }
