name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - actions

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
    steps:
      - name: cache mingw
        id: cache-mingw4
        uses: actions/cache@v1.0.3
        with:
          path: D:\a\_temp\msys
          key: windows-2016-msys4
      - uses: numworks/setup-msys2@v1
        if: steps.cache-mingw4.outputs.cache-hit != 'true'
        with:
          msystem: MINGW64
      - name: Install dependens
        if: steps.cache-mingw4.outputs.cache-hit != 'true'
        run: |
          $env:PATH="D:\a\_temp\msys;$env:PATH"
          msys2do pacman -S --noconfirm mingw-w64-x86_64-gcc make autoconf automake msys/libtool pkg-config openssl-devel
      - name: build
        run: |
          $env:PATH="D:\a\_temp\msys;D:\a\_temp\msys\usr\bin;D:\a\_temp\msys\msys64\usr\bin;D:\a\_temp\msys\msys64\mingw64\bin;$env:PATH"
          msys2do pacman -S --noconfirm tree
          find /d/a/_temp/msys -name tree

          
          
