name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - actions

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
    #  - uses: actions/checkout@v2.0.0
      - name: build
        run: |
          pwd
          ls a
          if [ $? != 0 ]; then
            echo fail
          else
            echo success
          fi
