name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - actions

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
    steps:
      - name: cache mingw
        id: cache-mingw2
        uses: actions/cache@v1.0.3
        with:
          path: D:\a\_temp\msys
          key: windows-2016-msys3
      - uses: numworks/setup-msys2@v1
        if: steps.cache-mingw2.outputs.cache-hit != 'true'
        with:
          msystem: MINGW64
      - name: build
        run: |
          $env:PATH="D:\a\_temp\msys\usr\bin;$env:PATH"
          ls D:\a\_temp\msys
          which make
          which gcc
          
