name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - actions

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2.0.0
      - name: install g++-multilib
        run: |
          sudo apt-get install g++-multilib
