name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '.mailmap'
      - 'ChangeLog*'
      - 'whatsnew*'
      - 'LICENSE'
    tags:
    - '*'

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]

    steps:
 #      - uses: actions/checkout@v2.0.0
      - name: Cache boost
        env:
          XX: ${VCPKG_INSTALLATION_ROOT}
        id: cache-boost
        uses: actions/cache@v2
        with:
          path: ~/../../vcpkg/installed
          key: ${{ runner.os }}-boost-v7
      - name: install
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          vcpkg install zlib:x64-windows
      - name: build
        run: |
          echo [0]$XX
          echo [1]$VCPKG_INSTALLATION_ROOT
          echo [2]$env:VCPKG_INSTALLATION_ROOT
          ls $env:VCPKG_INSTALLATION_ROOT\installed\x64-windows\lib
          
          
