name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
#       - uses: actions/checkout@v2.0.0
      - name: build
        env:
          CTX: ${{toJson(github)}}
          JOBS: ${{ toJson(job) }}
          COMMITID: ${{ github.sha }}
        shell: bash
        run: |
          echo [1]:${COMMITID:0:7}
          echo name=====${{github.event.head_commit.author.name}}
          echo email=====${{github.event.head_commit.author.email}}
          echo commit_id=====${{ github.sha }}
          echo commit_id=====${commit_id:0:7}
          echo owner.name===${{github.event.repository.owner.name}}
          echo [2]:"${{ github.sha }}"
          echo [3]:"$CTX"
