name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016]
    steps:
#       - uses: actions/checkout@v2.0.0
      - name: build
        run: |
          try {
            ls a 2>$null
            if (!$?) {
              echo shibail
              ls 
            } else {
              echo xxxxxxxxxxxxx
            }
          } catch {
            echo incatch
            pwd
            echo endend
          }
