name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - actions

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2.0.0
      - name: build
        run: |
          git branch
          git checkout gh-pages
          git rm -r *
          touch index.html
          echo "mssage from github actions" > index.html
          git commit -am "update"
          git push
