name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        pattern: [0, 1]
    steps:
      - name: install
        run: |
          sudo rm -f /etc/apt/sources.list.d/dotnetdev.list /etc/apt/sources.list.d/microsoft-prod.list /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install g++-multilib
