name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        pattern: [0, 1]
    steps:
      - name: install
        run: |
          sudo apt-get install g++-multilib
