name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - actions

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
    steps:
      - uses: numworks/setup-msys2@v1
        with: 
          msystem: MINGW64
      - name: install dependens
        run: |
          msys2do pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config make autoconf automake msys/libtool pkg-config openssl-devel
      - name: build and test
        env:
          OPENSSL_ROOT_DIR: D:/a/_temp/msys/msys64/usr
          MPATH: D:/a/_temp/msys/msys64/mingw64/bin;D:/a/_temp/msys/msys64/usr/bin
          EVENT_TESTS_PARALLEL: 1
          EVENT_BUILD_PARALLEL: 10 
        shell: powershell
        run: |
          $env:PATH="D:\a\_temp\msys\msys64\usr\bin;$env:PATH"
          echo PATH:$env:PATH
          openssl version
          ls D:\a\_temp\msys\msys64\usr
          ls D:\a\_temp\msys\msys64\usr\lib
          ls D:\a\_temp\msys\msys64\usr\lib\openssl
          bash.exe -c "which make"
          bash.exe -c "which autoconf"
          bash.exe -c "which automake"
          bash.exe -c "which pkg-config"
          D:\a\_temp\msys\msys64\usr\bin\bash.exe -c "which openssl"
