name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - actions

jobs:
  windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2016, windows-2019]
    steps:
      - name: find openssl on windows
        run: |
          echo "VCPKG_INSTALLATION_ROOT: $env:VCPKG_INSTALLATION_ROOT"
          ls $env:VCPKG_INSTALLATION_ROOT
          openssl version
          where openssl
          Get-Command openssl
          python -version
          python3 -version
